// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: local_rpc.proto

package localgrpcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalhostAPIService_WelcomeClient_FullMethodName          = "/localgrpcproto.LocalhostAPIService/WelcomeClient"
	LocalhostAPIService_AddVMInstanceByProcess_FullMethodName = "/localgrpcproto.LocalhostAPIService/AddVMInstanceByProcess"
	LocalhostAPIService_ListVMs_FullMethodName                = "/localgrpcproto.LocalhostAPIService/ListVMs"
	LocalhostAPIService_GetVMDetails_FullMethodName           = "/localgrpcproto.LocalhostAPIService/GetVMDetails"
	LocalhostAPIService_CoreToProcessControl_FullMethodName   = "/localgrpcproto.LocalhostAPIService/CoreToProcessControl"
)

// LocalhostAPIServiceClient is the client API for LocalhostAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocalhostAPIServiceClient interface {
	// Wird verwendet damit ein Client seine Sitzungsdaten angeben kann
	WelcomeClient(ctx context.Context, in *ClientWelcomeRequest, opts ...grpc.CallOption) (*ServerWelcomeResponse, error)
	// Wird verwendet um von einem Client aus eine neue VM zu Registrieren
	AddVMInstanceByProcess(ctx context.Context, in *VMClientRegisterRequest, opts ...grpc.CallOption) (*VMClientRegisterResponse, error)
	// Ruft eine Liste, aller Verfügabren VM's ab
	ListVMs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VmListResponse, error)
	// Ruft alle Details einer VM ab
	GetVMDetails(ctx context.Context, in *VmDetailsParms, opts ...grpc.CallOption) (*VmDetailsResponse, error)
	// Wird verwendet um den Prozess vom Core aus zu Kontrollieren
	CoreToProcessControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessControlPackage, ProcessControlPackage], error)
}

type localhostAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalhostAPIServiceClient(cc grpc.ClientConnInterface) LocalhostAPIServiceClient {
	return &localhostAPIServiceClient{cc}
}

func (c *localhostAPIServiceClient) WelcomeClient(ctx context.Context, in *ClientWelcomeRequest, opts ...grpc.CallOption) (*ServerWelcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerWelcomeResponse)
	err := c.cc.Invoke(ctx, LocalhostAPIService_WelcomeClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localhostAPIServiceClient) AddVMInstanceByProcess(ctx context.Context, in *VMClientRegisterRequest, opts ...grpc.CallOption) (*VMClientRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMClientRegisterResponse)
	err := c.cc.Invoke(ctx, LocalhostAPIService_AddVMInstanceByProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localhostAPIServiceClient) ListVMs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VmListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmListResponse)
	err := c.cc.Invoke(ctx, LocalhostAPIService_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localhostAPIServiceClient) GetVMDetails(ctx context.Context, in *VmDetailsParms, opts ...grpc.CallOption) (*VmDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmDetailsResponse)
	err := c.cc.Invoke(ctx, LocalhostAPIService_GetVMDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localhostAPIServiceClient) CoreToProcessControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessControlPackage, ProcessControlPackage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalhostAPIService_ServiceDesc.Streams[0], LocalhostAPIService_CoreToProcessControl_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessControlPackage, ProcessControlPackage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalhostAPIService_CoreToProcessControlClient = grpc.BidiStreamingClient[ProcessControlPackage, ProcessControlPackage]

// LocalhostAPIServiceServer is the server API for LocalhostAPIService service.
// All implementations must embed UnimplementedLocalhostAPIServiceServer
// for forward compatibility.
type LocalhostAPIServiceServer interface {
	// Wird verwendet damit ein Client seine Sitzungsdaten angeben kann
	WelcomeClient(context.Context, *ClientWelcomeRequest) (*ServerWelcomeResponse, error)
	// Wird verwendet um von einem Client aus eine neue VM zu Registrieren
	AddVMInstanceByProcess(context.Context, *VMClientRegisterRequest) (*VMClientRegisterResponse, error)
	// Ruft eine Liste, aller Verfügabren VM's ab
	ListVMs(context.Context, *emptypb.Empty) (*VmListResponse, error)
	// Ruft alle Details einer VM ab
	GetVMDetails(context.Context, *VmDetailsParms) (*VmDetailsResponse, error)
	// Wird verwendet um den Prozess vom Core aus zu Kontrollieren
	CoreToProcessControl(grpc.BidiStreamingServer[ProcessControlPackage, ProcessControlPackage]) error
	mustEmbedUnimplementedLocalhostAPIServiceServer()
}

// UnimplementedLocalhostAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalhostAPIServiceServer struct{}

func (UnimplementedLocalhostAPIServiceServer) WelcomeClient(context.Context, *ClientWelcomeRequest) (*ServerWelcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WelcomeClient not implemented")
}
func (UnimplementedLocalhostAPIServiceServer) AddVMInstanceByProcess(context.Context, *VMClientRegisterRequest) (*VMClientRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVMInstanceByProcess not implemented")
}
func (UnimplementedLocalhostAPIServiceServer) ListVMs(context.Context, *emptypb.Empty) (*VmListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedLocalhostAPIServiceServer) GetVMDetails(context.Context, *VmDetailsParms) (*VmDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVMDetails not implemented")
}
func (UnimplementedLocalhostAPIServiceServer) CoreToProcessControl(grpc.BidiStreamingServer[ProcessControlPackage, ProcessControlPackage]) error {
	return status.Errorf(codes.Unimplemented, "method CoreToProcessControl not implemented")
}
func (UnimplementedLocalhostAPIServiceServer) mustEmbedUnimplementedLocalhostAPIServiceServer() {}
func (UnimplementedLocalhostAPIServiceServer) testEmbeddedByValue()                             {}

// UnsafeLocalhostAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalhostAPIServiceServer will
// result in compilation errors.
type UnsafeLocalhostAPIServiceServer interface {
	mustEmbedUnimplementedLocalhostAPIServiceServer()
}

func RegisterLocalhostAPIServiceServer(s grpc.ServiceRegistrar, srv LocalhostAPIServiceServer) {
	// If the following call pancis, it indicates UnimplementedLocalhostAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalhostAPIService_ServiceDesc, srv)
}

func _LocalhostAPIService_WelcomeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientWelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalhostAPIServiceServer).WelcomeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalhostAPIService_WelcomeClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalhostAPIServiceServer).WelcomeClient(ctx, req.(*ClientWelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalhostAPIService_AddVMInstanceByProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMClientRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalhostAPIServiceServer).AddVMInstanceByProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalhostAPIService_AddVMInstanceByProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalhostAPIServiceServer).AddVMInstanceByProcess(ctx, req.(*VMClientRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalhostAPIService_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalhostAPIServiceServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalhostAPIService_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalhostAPIServiceServer).ListVMs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalhostAPIService_GetVMDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmDetailsParms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalhostAPIServiceServer).GetVMDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalhostAPIService_GetVMDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalhostAPIServiceServer).GetVMDetails(ctx, req.(*VmDetailsParms))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalhostAPIService_CoreToProcessControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalhostAPIServiceServer).CoreToProcessControl(&grpc.GenericServerStream[ProcessControlPackage, ProcessControlPackage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalhostAPIService_CoreToProcessControlServer = grpc.BidiStreamingServer[ProcessControlPackage, ProcessControlPackage]

// LocalhostAPIService_ServiceDesc is the grpc.ServiceDesc for LocalhostAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalhostAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "localgrpcproto.LocalhostAPIService",
	HandlerType: (*LocalhostAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WelcomeClient",
			Handler:    _LocalhostAPIService_WelcomeClient_Handler,
		},
		{
			MethodName: "AddVMInstanceByProcess",
			Handler:    _LocalhostAPIService_AddVMInstanceByProcess_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _LocalhostAPIService_ListVMs_Handler,
		},
		{
			MethodName: "GetVMDetails",
			Handler:    _LocalhostAPIService_GetVMDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CoreToProcessControl",
			Handler:       _LocalhostAPIService_CoreToProcessControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "local_rpc.proto",
}
