// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: local_rpc.proto

package localgrpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientType int32

const (
	ClientType_CLI ClientType = 0
	ClientType_VM  ClientType = 1
	ClientType_API ClientType = 2
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "CLI",
		1: "VM",
		2: "API",
	}
	ClientType_value = map[string]int32{
		"CLI": 0,
		"VM":  1,
		"API": 2,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_local_rpc_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_local_rpc_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{0}
}

type ClientMethode int32

const (
	ClientMethode_SYSTEM ClientMethode = 0
	ClientMethode_USER   ClientMethode = 1
)

// Enum value maps for ClientMethode.
var (
	ClientMethode_name = map[int32]string{
		0: "SYSTEM",
		1: "USER",
	}
	ClientMethode_value = map[string]int32{
		"SYSTEM": 0,
		"USER":   1,
	}
)

func (x ClientMethode) Enum() *ClientMethode {
	p := new(ClientMethode)
	*p = x
	return p
}

func (x ClientMethode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMethode) Descriptor() protoreflect.EnumDescriptor {
	return file_local_rpc_proto_enumTypes[1].Descriptor()
}

func (ClientMethode) Type() protoreflect.EnumType {
	return &file_local_rpc_proto_enumTypes[1]
}

func (x ClientMethode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMethode.Descriptor instead.
func (ClientMethode) EnumDescriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{1}
}

type VMClientRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifest   []byte `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Signature  []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ScriptHash string `protobuf:"bytes,3,opt,name=scriptHash,proto3" json:"scriptHash,omitempty"`
	ProcessId  string `protobuf:"bytes,4,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Kid        string `protobuf:"bytes,5,opt,name=kid,proto3" json:"kid,omitempty"`
}

func (x *VMClientRegisterRequest) Reset() {
	*x = VMClientRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMClientRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMClientRegisterRequest) ProtoMessage() {}

func (x *VMClientRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMClientRegisterRequest.ProtoReflect.Descriptor instead.
func (*VMClientRegisterRequest) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *VMClientRegisterRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *VMClientRegisterRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VMClientRegisterRequest) GetScriptHash() string {
	if x != nil {
		return x.ScriptHash
	}
	return ""
}

func (x *VMClientRegisterRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *VMClientRegisterRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

type VMClientRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vmid string `protobuf:"bytes,1,opt,name=vmid,proto3" json:"vmid,omitempty"`
}

func (x *VMClientRegisterResponse) Reset() {
	*x = VMClientRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMClientRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMClientRegisterResponse) ProtoMessage() {}

func (x *VMClientRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMClientRegisterResponse.ProtoReflect.Descriptor instead.
func (*VMClientRegisterResponse) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *VMClientRegisterResponse) GetVmid() string {
	if x != nil {
		return x.Vmid
	}
	return ""
}

type ClientWelcomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       uint64        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ClientType    ClientType    `protobuf:"varint,2,opt,name=client_type,json=clientType,proto3,enum=localgrpcproto.ClientType" json:"client_type,omitempty"`
	ClientMethode ClientMethode `protobuf:"varint,3,opt,name=client_methode,json=clientMethode,proto3,enum=localgrpcproto.ClientMethode" json:"client_methode,omitempty"`
}

func (x *ClientWelcomeRequest) Reset() {
	*x = ClientWelcomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientWelcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWelcomeRequest) ProtoMessage() {}

func (x *ClientWelcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWelcomeRequest.ProtoReflect.Descriptor instead.
func (*ClientWelcomeRequest) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ClientWelcomeRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientWelcomeRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLI
}

func (x *ClientWelcomeRequest) GetClientMethode() ClientMethode {
	if x != nil {
		return x.ClientMethode
	}
	return ClientMethode_SYSTEM
}

type ServerWelcomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ProcessId string `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Accepted  bool   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason    string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ServerWelcomeResponse) Reset() {
	*x = ServerWelcomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerWelcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerWelcomeResponse) ProtoMessage() {}

func (x *ServerWelcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerWelcomeResponse.ProtoReflect.Descriptor instead.
func (*ServerWelcomeResponse) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ServerWelcomeResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerWelcomeResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ServerWelcomeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ServerWelcomeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ProcessTransport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*ProcessTransport_WelcomeRequest
	Request isProcessTransport_Request `protobuf_oneof:"Request"`
	// Types that are assignable to Respone:
	//
	//	*ProcessTransport_WelcomeResponse
	Respone isProcessTransport_Respone `protobuf_oneof:"Respone"`
}

func (x *ProcessTransport) Reset() {
	*x = ProcessTransport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransport) ProtoMessage() {}

func (x *ProcessTransport) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransport.ProtoReflect.Descriptor instead.
func (*ProcessTransport) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{4}
}

func (m *ProcessTransport) GetRequest() isProcessTransport_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ProcessTransport) GetWelcomeRequest() *ClientWelcomeRequest {
	if x, ok := x.GetRequest().(*ProcessTransport_WelcomeRequest); ok {
		return x.WelcomeRequest
	}
	return nil
}

func (m *ProcessTransport) GetRespone() isProcessTransport_Respone {
	if m != nil {
		return m.Respone
	}
	return nil
}

func (x *ProcessTransport) GetWelcomeResponse() *ServerWelcomeResponse {
	if x, ok := x.GetRespone().(*ProcessTransport_WelcomeResponse); ok {
		return x.WelcomeResponse
	}
	return nil
}

type isProcessTransport_Request interface {
	isProcessTransport_Request()
}

type ProcessTransport_WelcomeRequest struct {
	WelcomeRequest *ClientWelcomeRequest `protobuf:"bytes,1,opt,name=welcomeRequest,proto3,oneof"`
}

func (*ProcessTransport_WelcomeRequest) isProcessTransport_Request() {}

type isProcessTransport_Respone interface {
	isProcessTransport_Respone()
}

type ProcessTransport_WelcomeResponse struct {
	WelcomeResponse *ServerWelcomeResponse `protobuf:"bytes,2,opt,name=welcomeResponse,proto3,oneof"`
}

func (*ProcessTransport_WelcomeResponse) isProcessTransport_Respone() {}

type VmInstanceTransport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*VmInstanceTransport_RegisterVmRequest
	Request isVmInstanceTransport_Request `protobuf_oneof:"Request"`
	// Types that are assignable to Response:
	//
	//	*VmInstanceTransport_RegisterVmResponse
	Response isVmInstanceTransport_Response `protobuf_oneof:"Response"`
}

func (x *VmInstanceTransport) Reset() {
	*x = VmInstanceTransport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmInstanceTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmInstanceTransport) ProtoMessage() {}

func (x *VmInstanceTransport) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmInstanceTransport.ProtoReflect.Descriptor instead.
func (*VmInstanceTransport) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{5}
}

func (m *VmInstanceTransport) GetRequest() isVmInstanceTransport_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *VmInstanceTransport) GetRegisterVmRequest() *VMClientRegisterRequest {
	if x, ok := x.GetRequest().(*VmInstanceTransport_RegisterVmRequest); ok {
		return x.RegisterVmRequest
	}
	return nil
}

func (m *VmInstanceTransport) GetResponse() isVmInstanceTransport_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *VmInstanceTransport) GetRegisterVmResponse() *VMClientRegisterResponse {
	if x, ok := x.GetResponse().(*VmInstanceTransport_RegisterVmResponse); ok {
		return x.RegisterVmResponse
	}
	return nil
}

type isVmInstanceTransport_Request interface {
	isVmInstanceTransport_Request()
}

type VmInstanceTransport_RegisterVmRequest struct {
	RegisterVmRequest *VMClientRegisterRequest `protobuf:"bytes,1,opt,name=register_vm_request,json=registerVmRequest,proto3,oneof"`
}

func (*VmInstanceTransport_RegisterVmRequest) isVmInstanceTransport_Request() {}

type isVmInstanceTransport_Response interface {
	isVmInstanceTransport_Response()
}

type VmInstanceTransport_RegisterVmResponse struct {
	RegisterVmResponse *VMClientRegisterResponse `protobuf:"bytes,2,opt,name=register_vm_response,json=registerVmResponse,proto3,oneof"`
}

func (*VmInstanceTransport_RegisterVmResponse) isVmInstanceTransport_Response() {}

var File_local_rpc_proto protoreflect.FileDescriptor

var file_local_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x17, 0x56, 0x4d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x18, 0x56, 0x4d, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x76, 0x6d, 0x69, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x14, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x44, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x52,
	0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x22, 0x84,
	0x01, 0x0a, 0x15, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xcb, 0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x4e, 0x0a, 0x0e, 0x77, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x77, 0x65, 0x6c, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x0f, 0x77, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x01, 0x52, 0x0f, 0x77, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x22, 0xe5, 0x01, 0x0a, 0x13, 0x56, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x59, 0x0a, 0x13, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x4d, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x56, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5c, 0x0a, 0x14, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x76, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x4d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x01,
	0x52, 0x12, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x26, 0x0a, 0x0a, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x4c, 0x49,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x4d, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x50,
	0x49, 0x10, 0x02, 0x2a, 0x25, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x32, 0xde, 0x01, 0x0a, 0x13, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x68, 0x6f, 0x73, 0x74, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x56, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x20, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x6f, 0x0a, 0x1f, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x56, 0x6d, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x23, 0x2e,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56,
	0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x1a, 0x23, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x2f,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_local_rpc_proto_rawDescOnce sync.Once
	file_local_rpc_proto_rawDescData = file_local_rpc_proto_rawDesc
)

func file_local_rpc_proto_rawDescGZIP() []byte {
	file_local_rpc_proto_rawDescOnce.Do(func() {
		file_local_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_local_rpc_proto_rawDescData)
	})
	return file_local_rpc_proto_rawDescData
}

var file_local_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_local_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_local_rpc_proto_goTypes = []any{
	(ClientType)(0),                  // 0: localgrpcproto.ClientType
	(ClientMethode)(0),               // 1: localgrpcproto.ClientMethode
	(*VMClientRegisterRequest)(nil),  // 2: localgrpcproto.VMClientRegisterRequest
	(*VMClientRegisterResponse)(nil), // 3: localgrpcproto.VMClientRegisterResponse
	(*ClientWelcomeRequest)(nil),     // 4: localgrpcproto.ClientWelcomeRequest
	(*ServerWelcomeResponse)(nil),    // 5: localgrpcproto.ServerWelcomeResponse
	(*ProcessTransport)(nil),         // 6: localgrpcproto.ProcessTransport
	(*VmInstanceTransport)(nil),      // 7: localgrpcproto.VmInstanceTransport
}
var file_local_rpc_proto_depIdxs = []int32{
	0, // 0: localgrpcproto.ClientWelcomeRequest.client_type:type_name -> localgrpcproto.ClientType
	1, // 1: localgrpcproto.ClientWelcomeRequest.client_methode:type_name -> localgrpcproto.ClientMethode
	4, // 2: localgrpcproto.ProcessTransport.welcomeRequest:type_name -> localgrpcproto.ClientWelcomeRequest
	5, // 3: localgrpcproto.ProcessTransport.welcomeResponse:type_name -> localgrpcproto.ServerWelcomeResponse
	2, // 4: localgrpcproto.VmInstanceTransport.register_vm_request:type_name -> localgrpcproto.VMClientRegisterRequest
	3, // 5: localgrpcproto.VmInstanceTransport.register_vm_response:type_name -> localgrpcproto.VMClientRegisterResponse
	6, // 6: localgrpcproto.LocalhostAPIService.SpawnProcess:input_type -> localgrpcproto.ProcessTransport
	7, // 7: localgrpcproto.LocalhostAPIService.RegisterAndLinkVmInstanceStream:input_type -> localgrpcproto.VmInstanceTransport
	6, // 8: localgrpcproto.LocalhostAPIService.SpawnProcess:output_type -> localgrpcproto.ProcessTransport
	7, // 9: localgrpcproto.LocalhostAPIService.RegisterAndLinkVmInstanceStream:output_type -> localgrpcproto.VmInstanceTransport
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_local_rpc_proto_init() }
func file_local_rpc_proto_init() {
	if File_local_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_local_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VMClientRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*VMClientRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ClientWelcomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ServerWelcomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ProcessTransport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*VmInstanceTransport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_local_rpc_proto_msgTypes[4].OneofWrappers = []any{
		(*ProcessTransport_WelcomeRequest)(nil),
		(*ProcessTransport_WelcomeResponse)(nil),
	}
	file_local_rpc_proto_msgTypes[5].OneofWrappers = []any{
		(*VmInstanceTransport_RegisterVmRequest)(nil),
		(*VmInstanceTransport_RegisterVmResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_local_rpc_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_local_rpc_proto_goTypes,
		DependencyIndexes: file_local_rpc_proto_depIdxs,
		EnumInfos:         file_local_rpc_proto_enumTypes,
		MessageInfos:      file_local_rpc_proto_msgTypes,
	}.Build()
	File_local_rpc_proto = out.File
	file_local_rpc_proto_rawDesc = nil
	file_local_rpc_proto_goTypes = nil
	file_local_rpc_proto_depIdxs = nil
}
