// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: protobuff/local_rpc.proto

package localgrpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientWelcomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ClientWelcomeRequest) Reset() {
	*x = ClientWelcomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientWelcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWelcomeRequest) ProtoMessage() {}

func (x *ClientWelcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWelcomeRequest.ProtoReflect.Descriptor instead.
func (*ClientWelcomeRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ClientWelcomeRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ClientWelcomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ClientWelcomeResponse) Reset() {
	*x = ClientWelcomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientWelcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWelcomeResponse) ProtoMessage() {}

func (x *ClientWelcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWelcomeResponse.ProtoReflect.Descriptor instead.
func (*ClientWelcomeResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ClientWelcomeResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type VmListEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	State     uint32 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	StartTime uint64 `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
}

func (x *VmListEntry) Reset() {
	*x = VmListEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmListEntry) ProtoMessage() {}

func (x *VmListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmListEntry.ProtoReflect.Descriptor instead.
func (*VmListEntry) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *VmListEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmListEntry) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *VmListEntry) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type VmListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vms []*VmListEntry `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
}

func (x *VmListResponse) Reset() {
	*x = VmListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmListResponse) ProtoMessage() {}

func (x *VmListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmListResponse.ProtoReflect.Descriptor instead.
func (*VmListResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *VmListResponse) GetVms() []*VmListEntry {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VmDetailWhitelistEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WildCardDomains []string `protobuf:"bytes,1,rep,name=WildCardDomains,proto3" json:"WildCardDomains,omitempty"`
	ExactDomains    []string `protobuf:"bytes,2,rep,name=ExactDomains,proto3" json:"ExactDomains,omitempty"`
	Methods         []string `protobuf:"bytes,3,rep,name=Methods,proto3" json:"Methods,omitempty"`
	IPv4List        []string `protobuf:"bytes,4,rep,name=IPv4List,proto3" json:"IPv4List,omitempty"`
	Ipv6List        []string `protobuf:"bytes,5,rep,name=Ipv6List,proto3" json:"Ipv6List,omitempty"`
}

func (x *VmDetailWhitelistEntry) Reset() {
	*x = VmDetailWhitelistEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailWhitelistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailWhitelistEntry) ProtoMessage() {}

func (x *VmDetailWhitelistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailWhitelistEntry.ProtoReflect.Descriptor instead.
func (*VmDetailWhitelistEntry) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *VmDetailWhitelistEntry) GetWildCardDomains() []string {
	if x != nil {
		return x.WildCardDomains
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetExactDomains() []string {
	if x != nil {
		return x.ExactDomains
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetIPv4List() []string {
	if x != nil {
		return x.IPv4List
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetIpv6List() []string {
	if x != nil {
		return x.Ipv6List
	}
	return nil
}

type VmDetailHostCAMemberEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Fingerprint string `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (x *VmDetailHostCAMemberEntry) Reset() {
	*x = VmDetailHostCAMemberEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailHostCAMemberEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailHostCAMemberEntry) ProtoMessage() {}

func (x *VmDetailHostCAMemberEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailHostCAMemberEntry.ProtoReflect.Descriptor instead.
func (*VmDetailHostCAMemberEntry) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *VmDetailHostCAMemberEntry) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *VmDetailHostCAMemberEntry) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type VmDetailDatabaseEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port     uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Database string `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
	Alias    string `protobuf:"bytes,7,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *VmDetailDatabaseEntry) Reset() {
	*x = VmDetailDatabaseEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailDatabaseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailDatabaseEntry) ProtoMessage() {}

func (x *VmDetailDatabaseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailDatabaseEntry.ProtoReflect.Descriptor instead.
func (*VmDetailDatabaseEntry) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *VmDetailDatabaseEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VmDetailDatabaseEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type VmDetailNodeJsModuleEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VmDetailNodeJsModuleEntry) Reset() {
	*x = VmDetailNodeJsModuleEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailNodeJsModuleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailNodeJsModuleEntry) ProtoMessage() {}

func (x *VmDetailNodeJsModuleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailNodeJsModuleEntry.ProtoReflect.Descriptor instead.
func (*VmDetailNodeJsModuleEntry) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *VmDetailNodeJsModuleEntry) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *VmDetailNodeJsModuleEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VmDetailNodeJsModuleEntryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsEnable bool                         `protobuf:"varint,1,opt,name=isEnable,proto3" json:"isEnable,omitempty"`
	Modules  []*VmDetailNodeJsModuleEntry `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *VmDetailNodeJsModuleEntryList) Reset() {
	*x = VmDetailNodeJsModuleEntryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailNodeJsModuleEntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailNodeJsModuleEntryList) ProtoMessage() {}

func (x *VmDetailNodeJsModuleEntryList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailNodeJsModuleEntryList.ProtoReflect.Descriptor instead.
func (*VmDetailNodeJsModuleEntryList) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *VmDetailNodeJsModuleEntryList) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *VmDetailNodeJsModuleEntryList) GetModules() []*VmDetailNodeJsModuleEntry {
	if x != nil {
		return x.Modules
	}
	return nil
}

type VmDetailSharedFunctionEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParmTypes []uint32 `protobuf:"varint,2,rep,packed,name=parmTypes,proto3" json:"parmTypes,omitempty"`
	Mode      string   `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *VmDetailSharedFunctionEntry) Reset() {
	*x = VmDetailSharedFunctionEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailSharedFunctionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailSharedFunctionEntry) ProtoMessage() {}

func (x *VmDetailSharedFunctionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailSharedFunctionEntry.ProtoReflect.Descriptor instead.
func (*VmDetailSharedFunctionEntry) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *VmDetailSharedFunctionEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmDetailSharedFunctionEntry) GetParmTypes() []uint32 {
	if x != nil {
		return x.ParmTypes
	}
	return nil
}

func (x *VmDetailSharedFunctionEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type VmDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         uint64                         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Owner           string                         `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Repourl         string                         `protobuf:"bytes,4,opt,name=repourl,proto3" json:"repourl,omitempty"`
	Mode            string                         `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	State           string                         `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	StartTimestamp  uint64                         `protobuf:"varint,7,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	Nodejs          *VmDetailNodeJsModuleEntryList `protobuf:"bytes,8,opt,name=nodejs,proto3" json:"nodejs,omitempty"`
	Whitelist       []*VmDetailWhitelistEntry      `protobuf:"bytes,9,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
	Hostcamember    []*VmDetailHostCAMemberEntry   `protobuf:"bytes,10,rep,name=hostcamember,proto3" json:"hostcamember,omitempty"`
	Databases       []*VmDetailDatabaseEntry       `protobuf:"bytes,11,rep,name=databases,proto3" json:"databases,omitempty"`
	SharedFunctions []*VmDetailSharedFunctionEntry `protobuf:"bytes,12,rep,name=sharedFunctions,proto3" json:"sharedFunctions,omitempty"`
}

func (x *VmDetailsResponse) Reset() {
	*x = VmDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailsResponse) ProtoMessage() {}

func (x *VmDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailsResponse.ProtoReflect.Descriptor instead.
func (*VmDetailsResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *VmDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmDetailsResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VmDetailsResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *VmDetailsResponse) GetRepourl() string {
	if x != nil {
		return x.Repourl
	}
	return ""
}

func (x *VmDetailsResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *VmDetailsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VmDetailsResponse) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *VmDetailsResponse) GetNodejs() *VmDetailNodeJsModuleEntryList {
	if x != nil {
		return x.Nodejs
	}
	return nil
}

func (x *VmDetailsResponse) GetWhitelist() []*VmDetailWhitelistEntry {
	if x != nil {
		return x.Whitelist
	}
	return nil
}

func (x *VmDetailsResponse) GetHostcamember() []*VmDetailHostCAMemberEntry {
	if x != nil {
		return x.Hostcamember
	}
	return nil
}

func (x *VmDetailsResponse) GetDatabases() []*VmDetailDatabaseEntry {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *VmDetailsResponse) GetSharedFunctions() []*VmDetailSharedFunctionEntry {
	if x != nil {
		return x.SharedFunctions
	}
	return nil
}

type VmDetailsParms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*VmDetailsParms_Name
	//	*VmDetailsParms_Id
	Value isVmDetailsParms_Value `protobuf_oneof:"value"`
}

func (x *VmDetailsParms) Reset() {
	*x = VmDetailsParms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_local_rpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailsParms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailsParms) ProtoMessage() {}

func (x *VmDetailsParms) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_local_rpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailsParms.ProtoReflect.Descriptor instead.
func (*VmDetailsParms) Descriptor() ([]byte, []int) {
	return file_protobuff_local_rpc_proto_rawDescGZIP(), []int{11}
}

func (m *VmDetailsParms) GetValue() isVmDetailsParms_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *VmDetailsParms) GetName() string {
	if x, ok := x.GetValue().(*VmDetailsParms_Name); ok {
		return x.Name
	}
	return ""
}

func (x *VmDetailsParms) GetId() string {
	if x, ok := x.GetValue().(*VmDetailsParms_Id); ok {
		return x.Id
	}
	return ""
}

type isVmDetailsParms_Value interface {
	isVmDetailsParms_Value()
}

type VmDetailsParms_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type VmDetailsParms_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*VmDetailsParms_Name) isVmDetailsParms_Value() {}

func (*VmDetailsParms_Id) isVmDetailsParms_Value() {}

var File_protobuff_local_rpc_proto protoreflect.FileDescriptor

var file_protobuff_local_rpc_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x15, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x65, 0x0a,
	0x0b, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0e, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x76, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x03, 0x76, 0x6d, 0x73, 0x22, 0xb8, 0x01, 0x0a, 0x16, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x28, 0x0a, 0x0f, 0x57, 0x69, 0x6c, 0x64, 0x43, 0x61, 0x72, 0x64, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x57, 0x69, 0x6c, 0x64, 0x43,
	0x61, 0x72, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x78,
	0x61, 0x63, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x45, 0x78, 0x61, 0x63, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x50, 0x76, 0x34,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x49, 0x50, 0x76, 0x34,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x70, 0x76, 0x36, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x49, 0x70, 0x76, 0x36, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x51, 0x0a, 0x19, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x48, 0x6f, 0x73, 0x74,
	0x43, 0x41, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x15, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x45, 0x0a, 0x19, 0x56, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x73, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x80,
	0x01, 0x0a, 0x1d, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x4a,
	0x73, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x43, 0x0a, 0x07,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56,
	0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x73, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x73, 0x22, 0x63, 0x0a, 0x1b, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0xbb, 0x04, 0x0a, 0x11, 0x56, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x45, 0x0a, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x6a, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x73, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x6a, 0x73, 0x12, 0x44, 0x0a, 0x09, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72,
	0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09,
	0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x0c, 0x68, 0x6f, 0x73,
	0x74, 0x63, 0x61, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x41, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74,
	0x63, 0x61, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x12, 0x55, 0x0a,
	0x0f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72,
	0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x41, 0x0a, 0x0e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x50, 0x61, 0x72, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x42, 0x07,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x89, 0x02, 0x0a, 0x13, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x68, 0x6f, 0x73, 0x74, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5c, 0x0a, 0x0d, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x24, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72,
	0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x07, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x4d, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1e, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x51, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x1e, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x50, 0x61, 0x72, 0x6d, 0x73,
	0x1a, 0x21, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuff_local_rpc_proto_rawDescOnce sync.Once
	file_protobuff_local_rpc_proto_rawDescData = file_protobuff_local_rpc_proto_rawDesc
)

func file_protobuff_local_rpc_proto_rawDescGZIP() []byte {
	file_protobuff_local_rpc_proto_rawDescOnce.Do(func() {
		file_protobuff_local_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuff_local_rpc_proto_rawDescData)
	})
	return file_protobuff_local_rpc_proto_rawDescData
}

var file_protobuff_local_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protobuff_local_rpc_proto_goTypes = []interface{}{
	(*ClientWelcomeRequest)(nil),          // 0: localgrpcproto.ClientWelcomeRequest
	(*ClientWelcomeResponse)(nil),         // 1: localgrpcproto.ClientWelcomeResponse
	(*VmListEntry)(nil),                   // 2: localgrpcproto.VmListEntry
	(*VmListResponse)(nil),                // 3: localgrpcproto.VmListResponse
	(*VmDetailWhitelistEntry)(nil),        // 4: localgrpcproto.VmDetailWhitelistEntry
	(*VmDetailHostCAMemberEntry)(nil),     // 5: localgrpcproto.VmDetailHostCAMemberEntry
	(*VmDetailDatabaseEntry)(nil),         // 6: localgrpcproto.VmDetailDatabaseEntry
	(*VmDetailNodeJsModuleEntry)(nil),     // 7: localgrpcproto.VmDetailNodeJsModuleEntry
	(*VmDetailNodeJsModuleEntryList)(nil), // 8: localgrpcproto.VmDetailNodeJsModuleEntryList
	(*VmDetailSharedFunctionEntry)(nil),   // 9: localgrpcproto.VmDetailSharedFunctionEntry
	(*VmDetailsResponse)(nil),             // 10: localgrpcproto.VmDetailsResponse
	(*VmDetailsParms)(nil),                // 11: localgrpcproto.VmDetailsParms
	(*emptypb.Empty)(nil),                 // 12: google.protobuf.Empty
}
var file_protobuff_local_rpc_proto_depIdxs = []int32{
	2,  // 0: localgrpcproto.VmListResponse.vms:type_name -> localgrpcproto.VmListEntry
	7,  // 1: localgrpcproto.VmDetailNodeJsModuleEntryList.modules:type_name -> localgrpcproto.VmDetailNodeJsModuleEntry
	8,  // 2: localgrpcproto.VmDetailsResponse.nodejs:type_name -> localgrpcproto.VmDetailNodeJsModuleEntryList
	4,  // 3: localgrpcproto.VmDetailsResponse.whitelist:type_name -> localgrpcproto.VmDetailWhitelistEntry
	5,  // 4: localgrpcproto.VmDetailsResponse.hostcamember:type_name -> localgrpcproto.VmDetailHostCAMemberEntry
	6,  // 5: localgrpcproto.VmDetailsResponse.databases:type_name -> localgrpcproto.VmDetailDatabaseEntry
	9,  // 6: localgrpcproto.VmDetailsResponse.sharedFunctions:type_name -> localgrpcproto.VmDetailSharedFunctionEntry
	0,  // 7: localgrpcproto.LocalhostAPIService.WelcomeClient:input_type -> localgrpcproto.ClientWelcomeRequest
	12, // 8: localgrpcproto.LocalhostAPIService.ListVMs:input_type -> google.protobuf.Empty
	11, // 9: localgrpcproto.LocalhostAPIService.GetVMDetails:input_type -> localgrpcproto.VmDetailsParms
	1,  // 10: localgrpcproto.LocalhostAPIService.WelcomeClient:output_type -> localgrpcproto.ClientWelcomeResponse
	3,  // 11: localgrpcproto.LocalhostAPIService.ListVMs:output_type -> localgrpcproto.VmListResponse
	10, // 12: localgrpcproto.LocalhostAPIService.GetVMDetails:output_type -> localgrpcproto.VmDetailsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protobuff_local_rpc_proto_init() }
func file_protobuff_local_rpc_proto_init() {
	if File_protobuff_local_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuff_local_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientWelcomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientWelcomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmListEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailWhitelistEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailHostCAMemberEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailDatabaseEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailNodeJsModuleEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailNodeJsModuleEntryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailSharedFunctionEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_local_rpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmDetailsParms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuff_local_rpc_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*VmDetailsParms_Name)(nil),
		(*VmDetailsParms_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuff_local_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_local_rpc_proto_goTypes,
		DependencyIndexes: file_protobuff_local_rpc_proto_depIdxs,
		MessageInfos:      file_protobuff_local_rpc_proto_msgTypes,
	}.Build()
	File_protobuff_local_rpc_proto = out.File
	file_protobuff_local_rpc_proto_rawDesc = nil
	file_protobuff_local_rpc_proto_goTypes = nil
	file_protobuff_local_rpc_proto_depIdxs = nil
}
