// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: local_rpc.proto

package localgrpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientType int32

const (
	ClientType_CLI ClientType = 0
	ClientType_VM  ClientType = 1
	ClientType_API ClientType = 2
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "CLI",
		1: "VM",
		2: "API",
	}
	ClientType_value = map[string]int32{
		"CLI": 0,
		"VM":  1,
		"API": 2,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_local_rpc_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_local_rpc_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{0}
}

type ClientMethode int32

const (
	ClientMethode_SYSTEM ClientMethode = 0
	ClientMethode_USER   ClientMethode = 1
)

// Enum value maps for ClientMethode.
var (
	ClientMethode_name = map[int32]string{
		0: "SYSTEM",
		1: "USER",
	}
	ClientMethode_value = map[string]int32{
		"SYSTEM": 0,
		"USER":   1,
	}
)

func (x ClientMethode) Enum() *ClientMethode {
	p := new(ClientMethode)
	*p = x
	return p
}

func (x ClientMethode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMethode) Descriptor() protoreflect.EnumDescriptor {
	return file_local_rpc_proto_enumTypes[1].Descriptor()
}

func (ClientMethode) Type() protoreflect.EnumType {
	return &file_local_rpc_proto_enumTypes[1]
}

func (x ClientMethode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMethode.Descriptor instead.
func (ClientMethode) EnumDescriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{1}
}

type VMClientRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifest   []byte `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Signature  []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ScriptHash string `protobuf:"bytes,3,opt,name=scriptHash,proto3" json:"scriptHash,omitempty"`
	ProcessId  string `protobuf:"bytes,4,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Kid        string `protobuf:"bytes,5,opt,name=kid,proto3" json:"kid,omitempty"`
}

func (x *VMClientRegisterRequest) Reset() {
	*x = VMClientRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMClientRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMClientRegisterRequest) ProtoMessage() {}

func (x *VMClientRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMClientRegisterRequest.ProtoReflect.Descriptor instead.
func (*VMClientRegisterRequest) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *VMClientRegisterRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *VMClientRegisterRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VMClientRegisterRequest) GetScriptHash() string {
	if x != nil {
		return x.ScriptHash
	}
	return ""
}

func (x *VMClientRegisterRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *VMClientRegisterRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

type VMClientRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vmid string `protobuf:"bytes,1,opt,name=vmid,proto3" json:"vmid,omitempty"`
}

func (x *VMClientRegisterResponse) Reset() {
	*x = VMClientRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMClientRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMClientRegisterResponse) ProtoMessage() {}

func (x *VMClientRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMClientRegisterResponse.ProtoReflect.Descriptor instead.
func (*VMClientRegisterResponse) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *VMClientRegisterResponse) GetVmid() string {
	if x != nil {
		return x.Vmid
	}
	return ""
}

type ClientWelcomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       uint64        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ClientType    ClientType    `protobuf:"varint,2,opt,name=client_type,json=clientType,proto3,enum=localgrpcproto.ClientType" json:"client_type,omitempty"`
	ClientMethode ClientMethode `protobuf:"varint,3,opt,name=client_methode,json=clientMethode,proto3,enum=localgrpcproto.ClientMethode" json:"client_methode,omitempty"`
}

func (x *ClientWelcomeRequest) Reset() {
	*x = ClientWelcomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientWelcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWelcomeRequest) ProtoMessage() {}

func (x *ClientWelcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWelcomeRequest.ProtoReflect.Descriptor instead.
func (*ClientWelcomeRequest) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ClientWelcomeRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientWelcomeRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLI
}

func (x *ClientWelcomeRequest) GetClientMethode() ClientMethode {
	if x != nil {
		return x.ClientMethode
	}
	return ClientMethode_SYSTEM
}

type ServerWelcomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ProcessId string `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Accepted  bool   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason    string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ServerWelcomeResponse) Reset() {
	*x = ServerWelcomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerWelcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerWelcomeResponse) ProtoMessage() {}

func (x *ServerWelcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerWelcomeResponse.ProtoReflect.Descriptor instead.
func (*ServerWelcomeResponse) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ServerWelcomeResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerWelcomeResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ServerWelcomeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ServerWelcomeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VmListEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	State     uint32 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	StartTime uint64 `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
}

func (x *VmListEntry) Reset() {
	*x = VmListEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmListEntry) ProtoMessage() {}

func (x *VmListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmListEntry.ProtoReflect.Descriptor instead.
func (*VmListEntry) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *VmListEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmListEntry) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *VmListEntry) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type VmListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vms []*VmListEntry `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
}

func (x *VmListResponse) Reset() {
	*x = VmListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmListResponse) ProtoMessage() {}

func (x *VmListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmListResponse.ProtoReflect.Descriptor instead.
func (*VmListResponse) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *VmListResponse) GetVms() []*VmListEntry {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VmDetailWhitelistEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WildCardDomains []string `protobuf:"bytes,1,rep,name=WildCardDomains,proto3" json:"WildCardDomains,omitempty"`
	ExactDomains    []string `protobuf:"bytes,2,rep,name=ExactDomains,proto3" json:"ExactDomains,omitempty"`
	Methods         []string `protobuf:"bytes,3,rep,name=Methods,proto3" json:"Methods,omitempty"`
	IPv4List        []string `protobuf:"bytes,4,rep,name=IPv4List,proto3" json:"IPv4List,omitempty"`
	Ipv6List        []string `protobuf:"bytes,5,rep,name=Ipv6List,proto3" json:"Ipv6List,omitempty"`
}

func (x *VmDetailWhitelistEntry) Reset() {
	*x = VmDetailWhitelistEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailWhitelistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailWhitelistEntry) ProtoMessage() {}

func (x *VmDetailWhitelistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailWhitelistEntry.ProtoReflect.Descriptor instead.
func (*VmDetailWhitelistEntry) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *VmDetailWhitelistEntry) GetWildCardDomains() []string {
	if x != nil {
		return x.WildCardDomains
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetExactDomains() []string {
	if x != nil {
		return x.ExactDomains
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetIPv4List() []string {
	if x != nil {
		return x.IPv4List
	}
	return nil
}

func (x *VmDetailWhitelistEntry) GetIpv6List() []string {
	if x != nil {
		return x.Ipv6List
	}
	return nil
}

type VmDetailHostCAMemberEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Fingerprint string `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (x *VmDetailHostCAMemberEntry) Reset() {
	*x = VmDetailHostCAMemberEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailHostCAMemberEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailHostCAMemberEntry) ProtoMessage() {}

func (x *VmDetailHostCAMemberEntry) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailHostCAMemberEntry.ProtoReflect.Descriptor instead.
func (*VmDetailHostCAMemberEntry) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *VmDetailHostCAMemberEntry) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *VmDetailHostCAMemberEntry) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type VmDetailDatabaseEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port     uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Database string `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
	Alias    string `protobuf:"bytes,7,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *VmDetailDatabaseEntry) Reset() {
	*x = VmDetailDatabaseEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailDatabaseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailDatabaseEntry) ProtoMessage() {}

func (x *VmDetailDatabaseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailDatabaseEntry.ProtoReflect.Descriptor instead.
func (*VmDetailDatabaseEntry) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *VmDetailDatabaseEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VmDetailDatabaseEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *VmDetailDatabaseEntry) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type VmDetailSharedFunctionEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParmTypes []uint32 `protobuf:"varint,2,rep,packed,name=parmTypes,proto3" json:"parmTypes,omitempty"`
	Mode      string   `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *VmDetailSharedFunctionEntry) Reset() {
	*x = VmDetailSharedFunctionEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailSharedFunctionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailSharedFunctionEntry) ProtoMessage() {}

func (x *VmDetailSharedFunctionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailSharedFunctionEntry.ProtoReflect.Descriptor instead.
func (*VmDetailSharedFunctionEntry) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *VmDetailSharedFunctionEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmDetailSharedFunctionEntry) GetParmTypes() []uint32 {
	if x != nil {
		return x.ParmTypes
	}
	return nil
}

func (x *VmDetailSharedFunctionEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type VmDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         uint64                         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Owner           string                         `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Repourl         string                         `protobuf:"bytes,4,opt,name=repourl,proto3" json:"repourl,omitempty"`
	Mode            string                         `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	State           string                         `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	StartTimestamp  uint64                         `protobuf:"varint,7,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	Whitelist       []*VmDetailWhitelistEntry      `protobuf:"bytes,8,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
	Hostcamember    []*VmDetailHostCAMemberEntry   `protobuf:"bytes,9,rep,name=hostcamember,proto3" json:"hostcamember,omitempty"`
	Databases       []*VmDetailDatabaseEntry       `protobuf:"bytes,10,rep,name=databases,proto3" json:"databases,omitempty"`
	SharedFunctions []*VmDetailSharedFunctionEntry `protobuf:"bytes,11,rep,name=sharedFunctions,proto3" json:"sharedFunctions,omitempty"`
}

func (x *VmDetailsResponse) Reset() {
	*x = VmDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailsResponse) ProtoMessage() {}

func (x *VmDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailsResponse.ProtoReflect.Descriptor instead.
func (*VmDetailsResponse) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *VmDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmDetailsResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VmDetailsResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *VmDetailsResponse) GetRepourl() string {
	if x != nil {
		return x.Repourl
	}
	return ""
}

func (x *VmDetailsResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *VmDetailsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VmDetailsResponse) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *VmDetailsResponse) GetWhitelist() []*VmDetailWhitelistEntry {
	if x != nil {
		return x.Whitelist
	}
	return nil
}

func (x *VmDetailsResponse) GetHostcamember() []*VmDetailHostCAMemberEntry {
	if x != nil {
		return x.Hostcamember
	}
	return nil
}

func (x *VmDetailsResponse) GetDatabases() []*VmDetailDatabaseEntry {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *VmDetailsResponse) GetSharedFunctions() []*VmDetailSharedFunctionEntry {
	if x != nil {
		return x.SharedFunctions
	}
	return nil
}

type VmDetailsParms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*VmDetailsParms_Name
	//	*VmDetailsParms_Id
	Value isVmDetailsParms_Value `protobuf_oneof:"value"`
}

func (x *VmDetailsParms) Reset() {
	*x = VmDetailsParms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmDetailsParms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetailsParms) ProtoMessage() {}

func (x *VmDetailsParms) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetailsParms.ProtoReflect.Descriptor instead.
func (*VmDetailsParms) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{11}
}

func (m *VmDetailsParms) GetValue() isVmDetailsParms_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *VmDetailsParms) GetName() string {
	if x, ok := x.GetValue().(*VmDetailsParms_Name); ok {
		return x.Name
	}
	return ""
}

func (x *VmDetailsParms) GetId() string {
	if x, ok := x.GetValue().(*VmDetailsParms_Id); ok {
		return x.Id
	}
	return ""
}

type isVmDetailsParms_Value interface {
	isVmDetailsParms_Value()
}

type VmDetailsParms_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type VmDetailsParms_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*VmDetailsParms_Name) isVmDetailsParms_Value() {}

func (*VmDetailsParms_Id) isVmDetailsParms_Value() {}

type PingPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingPong) Reset() {
	*x = PingPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPong) ProtoMessage() {}

func (x *PingPong) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPong.ProtoReflect.Descriptor instead.
func (*PingPong) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{12}
}

type ProcessControlPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//
	//	*ProcessControlPackage_RegisterProcess
	Req isProcessControlPackage_Req `protobuf_oneof:"req"`
}

func (x *ProcessControlPackage) Reset() {
	*x = ProcessControlPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_rpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessControlPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessControlPackage) ProtoMessage() {}

func (x *ProcessControlPackage) ProtoReflect() protoreflect.Message {
	mi := &file_local_rpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessControlPackage.ProtoReflect.Descriptor instead.
func (*ProcessControlPackage) Descriptor() ([]byte, []int) {
	return file_local_rpc_proto_rawDescGZIP(), []int{13}
}

func (m *ProcessControlPackage) GetReq() isProcessControlPackage_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *ProcessControlPackage) GetRegisterProcess() string {
	if x, ok := x.GetReq().(*ProcessControlPackage_RegisterProcess); ok {
		return x.RegisterProcess
	}
	return ""
}

type isProcessControlPackage_Req interface {
	isProcessControlPackage_Req()
}

type ProcessControlPackage_RegisterProcess struct {
	RegisterProcess string `protobuf:"bytes,1,opt,name=register_process,json=registerProcess,proto3,oneof"`
}

func (*ProcessControlPackage_RegisterProcess) isProcessControlPackage_Req() {}

var File_local_rpc_proto protoreflect.FileDescriptor

var file_local_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4,
	0x01, 0x0a, 0x17, 0x56, 0x4d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x18, 0x56, 0x4d, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x76, 0x6d, 0x69, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x44, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x52, 0x0d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x15,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x65, 0x0a, 0x0b, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0e, 0x56, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x76,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x76, 0x6d, 0x73, 0x22, 0xb8, 0x01, 0x0a, 0x16, 0x56,
	0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x57, 0x69, 0x6c, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f,
	0x57, 0x69, 0x6c, 0x64, 0x43, 0x61, 0x72, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x45, 0x78, 0x61, 0x63, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x78, 0x61, 0x63, 0x74, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x50, 0x76, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x49, 0x50, 0x76, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x70, 0x76,
	0x36, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x49, 0x70, 0x76,
	0x36, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x19, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x41, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x15, 0x56, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x63, 0x0a, 0x1b,
	0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x22, 0xf4, 0x03, 0x0a, 0x11, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x70, 0x6f, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x44, 0x0a, 0x09, 0x77, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x09, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4d, 0x0a,
	0x0c, 0x68, 0x6f, 0x73, 0x74, 0x63, 0x61, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x48, 0x6f, 0x73,
	0x74, 0x43, 0x41, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c,
	0x68, 0x6f, 0x73, 0x74, 0x63, 0x61, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x73, 0x12, 0x55, 0x0a, 0x0f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x41, 0x0a, 0x0e, 0x56, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x50, 0x61, 0x72, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02,
	0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x50,
	0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x4b, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x12, 0x2b, 0x0a, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42, 0x05, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x2a, 0x26, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x4c, 0x49, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x56,
	0x4d, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x10, 0x02, 0x2a, 0x25, 0x0a, 0x0d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45,
	0x52, 0x10, 0x01, 0x32, 0xe0, 0x03, 0x0a, 0x13, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x68, 0x6f, 0x73,
	0x74, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x57,
	0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x16, 0x41, 0x64, 0x64,
	0x56, 0x4d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x27, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x4d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x4d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x4d,
	0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x56, 0x4d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1e, 0x2e, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x50, 0x61, 0x72, 0x6d, 0x73, 0x1a, 0x21, 0x2e, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x14,
	0x43, 0x6f, 0x72, 0x65, 0x54, 0x6f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x12, 0x25, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x1a, 0x25, 0x2e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_local_rpc_proto_rawDescOnce sync.Once
	file_local_rpc_proto_rawDescData = file_local_rpc_proto_rawDesc
)

func file_local_rpc_proto_rawDescGZIP() []byte {
	file_local_rpc_proto_rawDescOnce.Do(func() {
		file_local_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_local_rpc_proto_rawDescData)
	})
	return file_local_rpc_proto_rawDescData
}

var file_local_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_local_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_local_rpc_proto_goTypes = []any{
	(ClientType)(0),                     // 0: localgrpcproto.ClientType
	(ClientMethode)(0),                  // 1: localgrpcproto.ClientMethode
	(*VMClientRegisterRequest)(nil),     // 2: localgrpcproto.VMClientRegisterRequest
	(*VMClientRegisterResponse)(nil),    // 3: localgrpcproto.VMClientRegisterResponse
	(*ClientWelcomeRequest)(nil),        // 4: localgrpcproto.ClientWelcomeRequest
	(*ServerWelcomeResponse)(nil),       // 5: localgrpcproto.ServerWelcomeResponse
	(*VmListEntry)(nil),                 // 6: localgrpcproto.VmListEntry
	(*VmListResponse)(nil),              // 7: localgrpcproto.VmListResponse
	(*VmDetailWhitelistEntry)(nil),      // 8: localgrpcproto.VmDetailWhitelistEntry
	(*VmDetailHostCAMemberEntry)(nil),   // 9: localgrpcproto.VmDetailHostCAMemberEntry
	(*VmDetailDatabaseEntry)(nil),       // 10: localgrpcproto.VmDetailDatabaseEntry
	(*VmDetailSharedFunctionEntry)(nil), // 11: localgrpcproto.VmDetailSharedFunctionEntry
	(*VmDetailsResponse)(nil),           // 12: localgrpcproto.VmDetailsResponse
	(*VmDetailsParms)(nil),              // 13: localgrpcproto.VmDetailsParms
	(*PingPong)(nil),                    // 14: localgrpcproto.PingPong
	(*ProcessControlPackage)(nil),       // 15: localgrpcproto.ProcessControlPackage
	(*emptypb.Empty)(nil),               // 16: google.protobuf.Empty
}
var file_local_rpc_proto_depIdxs = []int32{
	0,  // 0: localgrpcproto.ClientWelcomeRequest.client_type:type_name -> localgrpcproto.ClientType
	1,  // 1: localgrpcproto.ClientWelcomeRequest.client_methode:type_name -> localgrpcproto.ClientMethode
	6,  // 2: localgrpcproto.VmListResponse.vms:type_name -> localgrpcproto.VmListEntry
	8,  // 3: localgrpcproto.VmDetailsResponse.whitelist:type_name -> localgrpcproto.VmDetailWhitelistEntry
	9,  // 4: localgrpcproto.VmDetailsResponse.hostcamember:type_name -> localgrpcproto.VmDetailHostCAMemberEntry
	10, // 5: localgrpcproto.VmDetailsResponse.databases:type_name -> localgrpcproto.VmDetailDatabaseEntry
	11, // 6: localgrpcproto.VmDetailsResponse.sharedFunctions:type_name -> localgrpcproto.VmDetailSharedFunctionEntry
	4,  // 7: localgrpcproto.LocalhostAPIService.WelcomeClient:input_type -> localgrpcproto.ClientWelcomeRequest
	2,  // 8: localgrpcproto.LocalhostAPIService.AddVMInstanceByProcess:input_type -> localgrpcproto.VMClientRegisterRequest
	16, // 9: localgrpcproto.LocalhostAPIService.ListVMs:input_type -> google.protobuf.Empty
	13, // 10: localgrpcproto.LocalhostAPIService.GetVMDetails:input_type -> localgrpcproto.VmDetailsParms
	15, // 11: localgrpcproto.LocalhostAPIService.CoreToProcessControl:input_type -> localgrpcproto.ProcessControlPackage
	5,  // 12: localgrpcproto.LocalhostAPIService.WelcomeClient:output_type -> localgrpcproto.ServerWelcomeResponse
	3,  // 13: localgrpcproto.LocalhostAPIService.AddVMInstanceByProcess:output_type -> localgrpcproto.VMClientRegisterResponse
	7,  // 14: localgrpcproto.LocalhostAPIService.ListVMs:output_type -> localgrpcproto.VmListResponse
	12, // 15: localgrpcproto.LocalhostAPIService.GetVMDetails:output_type -> localgrpcproto.VmDetailsResponse
	15, // 16: localgrpcproto.LocalhostAPIService.CoreToProcessControl:output_type -> localgrpcproto.ProcessControlPackage
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_local_rpc_proto_init() }
func file_local_rpc_proto_init() {
	if File_local_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_local_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VMClientRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*VMClientRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ClientWelcomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ServerWelcomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*VmListEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*VmListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*VmDetailWhitelistEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*VmDetailHostCAMemberEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*VmDetailDatabaseEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*VmDetailSharedFunctionEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*VmDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*VmDetailsParms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*PingPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_rpc_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ProcessControlPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_local_rpc_proto_msgTypes[11].OneofWrappers = []any{
		(*VmDetailsParms_Name)(nil),
		(*VmDetailsParms_Id)(nil),
	}
	file_local_rpc_proto_msgTypes[13].OneofWrappers = []any{
		(*ProcessControlPackage_RegisterProcess)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_local_rpc_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_local_rpc_proto_goTypes,
		DependencyIndexes: file_local_rpc_proto_depIdxs,
		EnumInfos:         file_local_rpc_proto_enumTypes,
		MessageInfos:      file_local_rpc_proto_msgTypes,
	}.Build()
	File_local_rpc_proto = out.File
	file_local_rpc_proto_rawDesc = nil
	file_local_rpc_proto_goTypes = nil
	file_local_rpc_proto_depIdxs = nil
}
