// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: protobuff/rpc.proto

package publicgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCFunctionParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Value:
	//
	//	*RPCFunctionParameter_StringValue
	//	*RPCFunctionParameter_NumberValue
	//	*RPCFunctionParameter_BooleanValue
	//	*RPCFunctionParameter_BytesValue
	//	*RPCFunctionParameter_TimestampValue
	//	*RPCFunctionParameter_ObjectValue
	//	*RPCFunctionParameter_ArrayValue
	Value isRPCFunctionParameter_Value `protobuf_oneof:"value"`
}

func (x *RPCFunctionParameter) Reset() {
	*x = RPCFunctionParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCFunctionParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCFunctionParameter) ProtoMessage() {}

func (x *RPCFunctionParameter) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCFunctionParameter.ProtoReflect.Descriptor instead.
func (*RPCFunctionParameter) Descriptor() ([]byte, []int) {
	return file_protobuff_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RPCFunctionParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *RPCFunctionParameter) GetValue() isRPCFunctionParameter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *RPCFunctionParameter) GetStringValue() string {
	if x, ok := x.GetValue().(*RPCFunctionParameter_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *RPCFunctionParameter) GetNumberValue() float64 {
	if x, ok := x.GetValue().(*RPCFunctionParameter_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (x *RPCFunctionParameter) GetBooleanValue() bool {
	if x, ok := x.GetValue().(*RPCFunctionParameter_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (x *RPCFunctionParameter) GetBytesValue() []byte {
	if x, ok := x.GetValue().(*RPCFunctionParameter_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (x *RPCFunctionParameter) GetTimestampValue() *timestamppb.Timestamp {
	if x, ok := x.GetValue().(*RPCFunctionParameter_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (x *RPCFunctionParameter) GetObjectValue() *structpb.Struct {
	if x, ok := x.GetValue().(*RPCFunctionParameter_ObjectValue); ok {
		return x.ObjectValue
	}
	return nil
}

func (x *RPCFunctionParameter) GetArrayValue() *ArrayValue {
	if x, ok := x.GetValue().(*RPCFunctionParameter_ArrayValue); ok {
		return x.ArrayValue
	}
	return nil
}

type isRPCFunctionParameter_Value interface {
	isRPCFunctionParameter_Value()
}

type RPCFunctionParameter_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type RPCFunctionParameter_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=numberValue,proto3,oneof"` // Kann Ganzzahlen und Fließkommazahlen repräsentieren
}

type RPCFunctionParameter_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=booleanValue,proto3,oneof"`
}

type RPCFunctionParameter_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytesValue,proto3,oneof"`
}

type RPCFunctionParameter_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestampValue,proto3,oneof"`
}

type RPCFunctionParameter_ObjectValue struct {
	ObjectValue *structpb.Struct `protobuf:"bytes,7,opt,name=objectValue,proto3,oneof"`
}

type RPCFunctionParameter_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,8,opt,name=arrayValue,proto3,oneof"`
}

func (*RPCFunctionParameter_StringValue) isRPCFunctionParameter_Value() {}

func (*RPCFunctionParameter_NumberValue) isRPCFunctionParameter_Value() {}

func (*RPCFunctionParameter_BooleanValue) isRPCFunctionParameter_Value() {}

func (*RPCFunctionParameter_BytesValue) isRPCFunctionParameter_Value() {}

func (*RPCFunctionParameter_TimestampValue) isRPCFunctionParameter_Value() {}

func (*RPCFunctionParameter_ObjectValue) isRPCFunctionParameter_Value() {}

func (*RPCFunctionParameter_ArrayValue) isRPCFunctionParameter_Value() {}

type ArrayValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*RPCFunctionParameter `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_protobuff_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ArrayValue) GetValues() []*RPCFunctionParameter {
	if x != nil {
		return x.Values
	}
	return nil
}

type RPCFunctionCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionName string                  `protobuf:"bytes,1,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Parms        []*RPCFunctionParameter `protobuf:"bytes,2,rep,name=parms,proto3" json:"parms,omitempty"`
}

func (x *RPCFunctionCall) Reset() {
	*x = RPCFunctionCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCFunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCFunctionCall) ProtoMessage() {}

func (x *RPCFunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCFunctionCall.ProtoReflect.Descriptor instead.
func (*RPCFunctionCall) Descriptor() ([]byte, []int) {
	return file_protobuff_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RPCFunctionCall) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *RPCFunctionCall) GetParms() []*RPCFunctionParameter {
	if x != nil {
		return x.Parms
	}
	return nil
}

type RPCResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Value:
	//
	//	*RPCResponseData_StringValue
	//	*RPCResponseData_NumberValue
	//	*RPCResponseData_BooleanValue
	//	*RPCResponseData_BytesValue
	//	*RPCResponseData_TimestampValue
	//	*RPCResponseData_ObjectValue
	//	*RPCResponseData_ArrayValue
	Value isRPCResponseData_Value `protobuf_oneof:"value"`
}

func (x *RPCResponseData) Reset() {
	*x = RPCResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponseData) ProtoMessage() {}

func (x *RPCResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponseData.ProtoReflect.Descriptor instead.
func (*RPCResponseData) Descriptor() ([]byte, []int) {
	return file_protobuff_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RPCResponseData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *RPCResponseData) GetValue() isRPCResponseData_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *RPCResponseData) GetStringValue() string {
	if x, ok := x.GetValue().(*RPCResponseData_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *RPCResponseData) GetNumberValue() float64 {
	if x, ok := x.GetValue().(*RPCResponseData_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (x *RPCResponseData) GetBooleanValue() bool {
	if x, ok := x.GetValue().(*RPCResponseData_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (x *RPCResponseData) GetBytesValue() []byte {
	if x, ok := x.GetValue().(*RPCResponseData_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (x *RPCResponseData) GetTimestampValue() *timestamppb.Timestamp {
	if x, ok := x.GetValue().(*RPCResponseData_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (x *RPCResponseData) GetObjectValue() *structpb.Struct {
	if x, ok := x.GetValue().(*RPCResponseData_ObjectValue); ok {
		return x.ObjectValue
	}
	return nil
}

func (x *RPCResponseData) GetArrayValue() *ArrayValue {
	if x, ok := x.GetValue().(*RPCResponseData_ArrayValue); ok {
		return x.ArrayValue
	}
	return nil
}

type isRPCResponseData_Value interface {
	isRPCResponseData_Value()
}

type RPCResponseData_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type RPCResponseData_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=numberValue,proto3,oneof"`
}

type RPCResponseData_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=booleanValue,proto3,oneof"`
}

type RPCResponseData_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytesValue,proto3,oneof"`
}

type RPCResponseData_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestampValue,proto3,oneof"`
}

type RPCResponseData_ObjectValue struct {
	ObjectValue *structpb.Struct `protobuf:"bytes,7,opt,name=objectValue,proto3,oneof"`
}

type RPCResponseData_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,8,opt,name=arrayValue,proto3,oneof"`
}

func (*RPCResponseData_StringValue) isRPCResponseData_Value() {}

func (*RPCResponseData_NumberValue) isRPCResponseData_Value() {}

func (*RPCResponseData_BooleanValue) isRPCResponseData_Value() {}

func (*RPCResponseData_BytesValue) isRPCResponseData_Value() {}

func (*RPCResponseData_TimestampValue) isRPCResponseData_Value() {}

func (*RPCResponseData_ObjectValue) isRPCResponseData_Value() {}

func (*RPCResponseData_ArrayValue) isRPCResponseData_Value() {}

type RPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *RPCResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error  string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // Optional in gRPC. Leerlassen, wenn kein Fehler vorliegt.
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RPCResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RPCResponse) GetData() *RPCResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RPCResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protobuff_rpc_proto protoreflect.FileDescriptor

var file_protobuff_rpc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70,
	0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x80, 0x03, 0x0a, 0x14, 0x52, 0x50, 0x43, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x22, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0c, 0x62,
	0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0a, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x44, 0x0a,
	0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x48, 0x00, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x38, 0x0a, 0x0a, 0x61, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0a,
	0x61, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x0a, 0x41, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x38, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x50, 0x43, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x6d, 0x0a, 0x0f, 0x52,
	0x50, 0x43, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x50, 0x43, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x52, 0x05, 0x70, 0x61, 0x72, 0x6d, 0x73, 0x22, 0xfb, 0x02, 0x0a, 0x0f, 0x52,
	0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0c, 0x62, 0x6f,
	0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x20, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x44, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6c, 0x0a, 0x0b, 0x52, 0x50, 0x43, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x50, 0x43, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x54, 0x0a, 0x0a, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x50, 0x43, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c,
	0x6c, 0x1a, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67,
	0x72, 0x70, 0x63, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuff_rpc_proto_rawDescOnce sync.Once
	file_protobuff_rpc_proto_rawDescData = file_protobuff_rpc_proto_rawDesc
)

func file_protobuff_rpc_proto_rawDescGZIP() []byte {
	file_protobuff_rpc_proto_rawDescOnce.Do(func() {
		file_protobuff_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuff_rpc_proto_rawDescData)
	})
	return file_protobuff_rpc_proto_rawDescData
}

var file_protobuff_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuff_rpc_proto_goTypes = []interface{}{
	(*RPCFunctionParameter)(nil),  // 0: publicgrpc.RPCFunctionParameter
	(*ArrayValue)(nil),            // 1: publicgrpc.ArrayValue
	(*RPCFunctionCall)(nil),       // 2: publicgrpc.RPCFunctionCall
	(*RPCResponseData)(nil),       // 3: publicgrpc.RPCResponseData
	(*RPCResponse)(nil),           // 4: publicgrpc.RPCResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
}
var file_protobuff_rpc_proto_depIdxs = []int32{
	5,  // 0: publicgrpc.RPCFunctionParameter.timestampValue:type_name -> google.protobuf.Timestamp
	6,  // 1: publicgrpc.RPCFunctionParameter.objectValue:type_name -> google.protobuf.Struct
	1,  // 2: publicgrpc.RPCFunctionParameter.arrayValue:type_name -> publicgrpc.ArrayValue
	0,  // 3: publicgrpc.ArrayValue.values:type_name -> publicgrpc.RPCFunctionParameter
	0,  // 4: publicgrpc.RPCFunctionCall.parms:type_name -> publicgrpc.RPCFunctionParameter
	5,  // 5: publicgrpc.RPCResponseData.timestampValue:type_name -> google.protobuf.Timestamp
	6,  // 6: publicgrpc.RPCResponseData.objectValue:type_name -> google.protobuf.Struct
	1,  // 7: publicgrpc.RPCResponseData.arrayValue:type_name -> publicgrpc.ArrayValue
	3,  // 8: publicgrpc.RPCResponse.data:type_name -> publicgrpc.RPCResponseData
	2,  // 9: publicgrpc.RPCService.CallFunction:input_type -> publicgrpc.RPCFunctionCall
	4,  // 10: publicgrpc.RPCService.CallFunction:output_type -> publicgrpc.RPCResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_protobuff_rpc_proto_init() }
func file_protobuff_rpc_proto_init() {
	if File_protobuff_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuff_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCFunctionParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCFunctionCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuff_rpc_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RPCFunctionParameter_StringValue)(nil),
		(*RPCFunctionParameter_NumberValue)(nil),
		(*RPCFunctionParameter_BooleanValue)(nil),
		(*RPCFunctionParameter_BytesValue)(nil),
		(*RPCFunctionParameter_TimestampValue)(nil),
		(*RPCFunctionParameter_ObjectValue)(nil),
		(*RPCFunctionParameter_ArrayValue)(nil),
	}
	file_protobuff_rpc_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*RPCResponseData_StringValue)(nil),
		(*RPCResponseData_NumberValue)(nil),
		(*RPCResponseData_BooleanValue)(nil),
		(*RPCResponseData_BytesValue)(nil),
		(*RPCResponseData_TimestampValue)(nil),
		(*RPCResponseData_ObjectValue)(nil),
		(*RPCResponseData_ArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuff_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_rpc_proto_goTypes,
		DependencyIndexes: file_protobuff_rpc_proto_depIdxs,
		MessageInfos:      file_protobuff_rpc_proto_msgTypes,
	}.Build()
	File_protobuff_rpc_proto = out.File
	file_protobuff_rpc_proto_rawDesc = nil
	file_protobuff_rpc_proto_goTypes = nil
	file_protobuff_rpc_proto_depIdxs = nil
}
