// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: protobuff/cli_rpc.proto

package cligrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientWelcomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ClientWelcomeRequest) Reset() {
	*x = ClientWelcomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_cli_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientWelcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWelcomeRequest) ProtoMessage() {}

func (x *ClientWelcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_cli_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWelcomeRequest.ProtoReflect.Descriptor instead.
func (*ClientWelcomeRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_cli_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ClientWelcomeRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ClientWelcomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ClientWelcomeResponse) Reset() {
	*x = ClientWelcomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_cli_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientWelcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWelcomeResponse) ProtoMessage() {}

func (x *ClientWelcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_cli_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWelcomeResponse.ProtoReflect.Descriptor instead.
func (*ClientWelcomeResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_cli_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ClientWelcomeResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type VmListEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id              string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	State           uint32   `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	StartTime       uint64   `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	SharedFunctions []string `protobuf:"bytes,5,rep,name=sharedFunctions,proto3" json:"sharedFunctions,omitempty"`
	NodeJsModules   []string `protobuf:"bytes,6,rep,name=nodeJsModules,proto3" json:"nodeJsModules,omitempty"`
	DomainWhiteList []string `protobuf:"bytes,7,rep,name=domainWhiteList,proto3" json:"domainWhiteList,omitempty"`
	SslMemberHashes []string `protobuf:"bytes,8,rep,name=sslMemberHashes,proto3" json:"sslMemberHashes,omitempty"`
}

func (x *VmListEntry) Reset() {
	*x = VmListEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_cli_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmListEntry) ProtoMessage() {}

func (x *VmListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_cli_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmListEntry.ProtoReflect.Descriptor instead.
func (*VmListEntry) Descriptor() ([]byte, []int) {
	return file_protobuff_cli_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *VmListEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmListEntry) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *VmListEntry) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VmListEntry) GetSharedFunctions() []string {
	if x != nil {
		return x.SharedFunctions
	}
	return nil
}

func (x *VmListEntry) GetNodeJsModules() []string {
	if x != nil {
		return x.NodeJsModules
	}
	return nil
}

func (x *VmListEntry) GetDomainWhiteList() []string {
	if x != nil {
		return x.DomainWhiteList
	}
	return nil
}

func (x *VmListEntry) GetSslMemberHashes() []string {
	if x != nil {
		return x.SslMemberHashes
	}
	return nil
}

type VmListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vms []*VmListEntry `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
}

func (x *VmListResponse) Reset() {
	*x = VmListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_cli_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmListResponse) ProtoMessage() {}

func (x *VmListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_cli_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmListResponse.ProtoReflect.Descriptor instead.
func (*VmListResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_cli_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *VmListResponse) GetVms() []*VmListEntry {
	if x != nil {
		return x.Vms
	}
	return nil
}

var File_protobuff_cli_rpc_proto protoreflect.FileDescriptor

var file_protobuff_cli_rpc_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x5f,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x69, 0x67, 0x72,
	0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x30, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x31, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x02, 0x0a, 0x0b, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x6f, 0x64, 0x65, 0x4a, 0x73,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x6e,
	0x6f, 0x64, 0x65, 0x4a, 0x73, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x57, 0x68, 0x69,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x73, 0x6c, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x73, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x22, 0x38, 0x0a, 0x0e, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x76, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x6c, 0x69, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x76, 0x6d, 0x73, 0x32, 0x98, 0x01, 0x0a, 0x0a, 0x43,
	0x4c, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x57, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x63, 0x6c, 0x69,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6c, 0x69, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x4c, 0x69, 0x73,
	0x74, 0x56, 0x4d, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x63,
	0x6c, 0x69, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63,
	0x6c, 0x69, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x63, 0x6c, 0x69, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuff_cli_rpc_proto_rawDescOnce sync.Once
	file_protobuff_cli_rpc_proto_rawDescData = file_protobuff_cli_rpc_proto_rawDesc
)

func file_protobuff_cli_rpc_proto_rawDescGZIP() []byte {
	file_protobuff_cli_rpc_proto_rawDescOnce.Do(func() {
		file_protobuff_cli_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuff_cli_rpc_proto_rawDescData)
	})
	return file_protobuff_cli_rpc_proto_rawDescData
}

var file_protobuff_cli_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuff_cli_rpc_proto_goTypes = []interface{}{
	(*ClientWelcomeRequest)(nil),  // 0: cligrpc.ClientWelcomeRequest
	(*ClientWelcomeResponse)(nil), // 1: cligrpc.ClientWelcomeResponse
	(*VmListEntry)(nil),           // 2: cligrpc.VmListEntry
	(*VmListResponse)(nil),        // 3: cligrpc.VmListResponse
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_protobuff_cli_rpc_proto_depIdxs = []int32{
	2, // 0: cligrpc.VmListResponse.vms:type_name -> cligrpc.VmListEntry
	0, // 1: cligrpc.CLIService.WelcomeClient:input_type -> cligrpc.ClientWelcomeRequest
	4, // 2: cligrpc.CLIService.ListVMs:input_type -> google.protobuf.Empty
	1, // 3: cligrpc.CLIService.WelcomeClient:output_type -> cligrpc.ClientWelcomeResponse
	3, // 4: cligrpc.CLIService.ListVMs:output_type -> cligrpc.VmListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuff_cli_rpc_proto_init() }
func file_protobuff_cli_rpc_proto_init() {
	if File_protobuff_cli_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuff_cli_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientWelcomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_cli_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientWelcomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_cli_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmListEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_cli_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuff_cli_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_cli_rpc_proto_goTypes,
		DependencyIndexes: file_protobuff_cli_rpc_proto_depIdxs,
		MessageInfos:      file_protobuff_cli_rpc_proto_msgTypes,
	}.Build()
	File_protobuff_cli_rpc_proto = out.File
	file_protobuff_cli_rpc_proto_rawDesc = nil
	file_protobuff_cli_rpc_proto_goTypes = nil
	file_protobuff_cli_rpc_proto_depIdxs = nil
}
